config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :containers
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/container.rb
class Container < ApplicationRecord
  validates :tag, presence: true, uniqueness: { scope: :user_id }
  belongs_to :user
  has_many :tasks, dependent: :destroy
  enum :color, { gray: 0, blue: 1, green: 2, red: 3, yellow: 4, purple: 5, lime: 6, navy: 7, olive: 8 }
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  belongs_to :container
  enum :status, { pending: 0, in_progress: 1, completed: 2, expired: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :containers, dependent: :destroy
  has_many :tasks, through: :containers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/containers_controller.rb
include ActionView::RecordIdentifier

class ContainersController < ApplicationController
  before_action :set_container, only: %i[show edit update destroy]

  def index
    @containers = current_user.containers.all
  end

  def show; end

  def new
    @container = current_user.containers.new
  end

  def edit; end

  def create
    @container = current_user.containers.new(container_params)

    respond_to do |format|
      if @container.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("containers", partial: "containers/container",
                                                                  locals: { container: @container })
        end
        format.html { redirect_to container_url(@container), notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @container.update(container_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@container, partial: "containers/container",
                                                                             locals: { container: @container })
        end
        format.html { redirect_to container_url(@container), notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @container.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@container) }
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_container
    @container = Container.find(params[:id])
  end

  def container_params
    params.require(:container).permit(:tag, :color)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def home; end
end

app/controllers/tasks_controller.rb
include ActionView::RecordIdentifier

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = current_user.tasks.all
  end

  def show; end

  def new
    @task = current_user.tasks.new
  end

  def edit; end

  def create
    @task = current_user.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.turbo_stream do
          render turbo_stream: turbo_stream.prepend("#{@task.container.id}-#{@task.status}", partial: "tasks/task",
                                                                                             locals: { task: @task })
        end
        format.html { redirect_to root_path, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(@task, partial: "tasks/task", locals: { task: @task })
        end
        format.html { redirect_to root_path, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: root_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@task) }
      format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :container_id, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/containers/_container.html.erb
<%= javascript_include_tag 'contextMenu' %>
<div id="<%= dom_id container %>" class="container-card" style="border-top: 10px solid <%= container.color %>" data-container-id="<%= container.id %>" oncontextmenu="showCombinedContextMenu(event)">
  <div class='container-title'>
    <b><%= container.tag %></b>
    <div>
      <span><%= link_to 'Edit', edit_container_path(container), data: { turbo_frame: "modal" }, class: 'button' %></span>
      <span> <%= link_to 'New Task', new_task_path, data: { turbo_frame: "modal" }, class: 'button' %> </span>
    </div>
  </div>
  <% container.tasks.order(:status).group_by(&:status).each do |status, tasks| %>
      <div class="status-card" id="status-card-<%= container.id %>-<%= status %>" data-expanded="true">
        <div class="status-card-header" onclick="toggleStatusCard('<%= container.id %>-<%= status %>')">
          <span><b><%= status %></b> </span>
          <span class="caret">&gt;</span>
          <span class="task-count"><%= tasks.count %> Tasks</span>
        </div>
      <div class="tasks-container">
        <div class="tasks-status-wrapper" id="<%= container.id %>-<%= status %>">
          <% tasks.each do |task| %>
            <%= render task %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="context-menu-container-<%= container.id %>" class="hidden">
  <ul>
    <li id="new-task-<%= container.id %>"><span>Add new task</span></li>
    <li><%= link_to "Edit container", edit_container_path(container), data: { turbo_frame: "modal" }, class: 'status-option'%></li>
    <li><%= button_to "Delete container", container, method: :delete, class: 'context-menu-delete' %></li>
  </ul>
</div>

app/views/containers/_form.html.erb
<%= form_with(model: container) do |form| %>
  <% if container.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

      <ul>
        <% container.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tag, style: "display: block" %>
    <%= form.text_area :tag %>
  </div>

   <div class="form-group">
    <%= form.label :color %>
    <%= form.select :color, options_for_select(Container.colors.keys, container.color), {}, { class: 'input' } %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/containers/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <h1>Editing container</h1>

    <%= render "form", container: @container %>

    <br>

    <div>
      <%= link_to "Cancel", "#", data:{
        controller: "modals",
        action: "modals#close"
      }, class: 'button' %>
    </div>
  </div>
<% end %>

app/views/containers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Containers</h1>

<div id="containers" class="container-wrapper">
  <% @containers.each do |container| %>
    <%= render container %>
  <% end %>
</div>

<div class="floating-buttons">
  <%= link_to 'New Container', new_container_path, class: 'floating-button' %>
</div>

app/views/containers/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <h1>New container</h1>

    <%= render "form", container: @container %>

    <br>

    <div>
      <%= link_to "Cancel", "#", data: {
        controller: "modals",
        action: "modals#close"
      }, class: "button" %>
    </div>
  </div>
<% end %>

app/views/containers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @container %>

<div>
  <%= link_to "Edit this container", edit_container_path(@container), class: 'button' %> |
  <%= link_to "Back to containers", containers_path, class: 'button' %>

  <%= button_to "Destroy this container", @container, method: :delete, class: 'delete-button' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <meta name="csrf-token" content="<%= form_authenticity_token %>">
  </head>

  <body>
    <%= turbo_frame_tag "modal" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/navbar', show_home_page: false %>
<% if notice.present? %>
  <div class="notice">
    <p><%= notice %></p>
  </div>
<% end %>
<div class="container-wrapper" id="containers">
  <% current_user.containers.group_by(&:tag).each do |tag, containers| %>
      <% containers.each do | container | %>
          <%= render container %>
      <% end %>
  <% end %>
</div>

<div class="floating-buttons">
  <%= link_to 'New Container', new_container_path, data:{ turbo_frame: "modal" }, class: 'floating-button' %>
</div>

app/views/shared/_navbar.html.erb
<!-- app/views/shared/_navbar.html.erb -->
<div class="navbar">
  <div class="navbar-email"><%= current_user.email %></div>
  <% if show_home_page %>
    <%= link_to 'Home', root_path, class: 'button' %>
  <% end %>
  <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'sign-out-button' %>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div class="error-messages">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_area :title, class: 'input' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'input' %>
  </div>

  <div class="form-group">
    <%= form.label :container_id %>
    <%= form.collection_select :container_id, current_user.containers, :id, :tag, {}, { class: 'input' } %>
  </div>

   <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Task.statuses.keys, task.status), {}, { class: 'input' } %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit', class: 'submit-button' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= javascript_include_tag 'task' %>

    <%= link_to task_path(task), data: { turbo_frame: "modal" }, class: 'task-card-link' do %>
      <div class="task-card" id="<%= dom_id task %>" data-task-id="<%= task.id %>" oncontextmenu="showCombinedContextMenu(event)">
        <b><%= task.title %></b><br>
        <p><%= task.description %></p><br>
      </div>
    <% end %>

<div id="context-menu-task-<%= task.id %>" class="hidden">
  <ul>
    <% Task.statuses.keys.excluding(task.status).each do |status_option| %>
      <li><%= button_to "Mark #{status_option}", task_path(task, task: { status: status_option }), method: :patch, class: 'status-option' %></li>
    <% end %>
    <li><%= link_to "Edit task", edit_task_path(task), data:{turbo_frame: "modal"}, class: 'status-option'%></li>
    <li><%= button_to "Delete task", task, method: :delete, class: 'context-menu-delete' %></li>
    <hr>
  </ul>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <%= render "form", task: @task %>
    <br>
    <div>
      <%= link_to "Cancel", '#', data:{
        controller: "modals",
        action: "modals#close"
      }, class: 'button' %>
    </div>
  </div>
<% end %>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
  <% end %>
</div>

<%= link_to "New task", new_task_path, class: 'button' %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
    <h1>New task</h1>

    <%= render "form", task: @task %>

    <br>

    <div>
      <%= link_to "Cancel", "#", data:{
        controller: "modals",
        action: "modals#close"
      }, class: 'button' %>
    </div>
  </div>
<% end %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag "modal" do %>
  <div class="modal">

    <%= render @task %>

    <div>
      <%= link_to "Edit this task", edit_task_path(@task), class: 'button'%> |
      <%= link_to "Cancel", "#", data:{
        controller: "modals",
        action: "modals#close"
        }, class: 'button'%>

      <%= button_to "Destroy this task", @task, method: :delete, class: 'delete-button' %>
    </div>
  </div>
<% end %>